#pragma once
/*
0. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_T2Sword_AttackCombo01_N
1. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_T2Sword_AttackNormal01_N
2. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_T2Sword_AttackNormal03_N
3. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_T2Sword_AttackNormal05_N
4. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_T2Sword_AttackParry_N_End
5. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_T2Sword_AttackParry_N_Loop
6. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_T2Sword_AttackParry_N_Start
7. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_T2Sword_AttackParryAttack_N
8. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_T2Sword_AttackSpawn_N
9. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_T2Sword_Deformation_N
10. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_T2Sword_Idle_N_Loop
11. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_T2Sword_Idle_N_Pose
12. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TAxe_AttackJump01_N
13. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TAxe_AttackKetsugi_N
14. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TAxe_AttackNormal01_N
15. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TAxe_AttackNormal02_N
16. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TAxe_AttackNormal03_N
17. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TAxe_AttackNormal04_N
18. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TAxe_Damage_BL
19. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TAxe_Damage_BL1
20. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TAxe_Damage_BR
21. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TAxe_Damage_FL
22. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TAxe_Damage_FR
23. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TAxe_Death_N
24. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TAxe_Down_N_End
25. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TAxe_Down_N_Loop
26. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TAxe_Down_N_Start
27. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TAxe_Idle_N_Loop
28. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TAxe_StatusAilment_Stun_N
29. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_Damage_BL
30. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_Damage_BR
31. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_Damage_FL
32. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_Damage_FR
33. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_Dodge_B
34. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_Dodge_L
35. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_Dodge_R
36. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_Down_N_End
37. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_Down_N_Loop
38. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_Down_N_Start
39. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_IdleTurn_L180
40. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_IdleTurn_L90
41. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_IdleTurn_R180
42. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_IdleTurn_R90
43. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_StatusAilment_Stun_N
44. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_Walk_B_Loop
45. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_Walk_BL_Loop
46. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_Walk_BR_Loop
47. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_Walk_F_Loop
48. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_Walk_FL_Loop
49. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_Walk_FR_Loop
50. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_Walk_L_Loop
51. Animation Name : SK_SkyBridgeBoss_LOD0.ao | AS_TSkgKing_TCmn_Walk_R_Loop
*/