//NS_BEGIN(Client)
//enum PLAYER_ANIMATION_KEY
//{
//    // ===== 피해 애니메이션 (0-3) =====
//    PLAYER_ANIM_DAMAGE_B = 0, PLAYER_ANIM_DAMAGE_F = 1, PLAYER_ANIM_DAMAGE_L = 2,
//    PLAYER_ANIM_DAMAGE_R = 3,
//
//    // ===== 달리기 애니메이션 (4-11) =====
//    PLAYER_ANIM_RUN_B_LOOP = 4, PLAYER_ANIM_RUN_B_END = 5, PLAYER_ANIM_RUN_F_LOOP = 6,
//    PLAYER_ANIM_RUN_F_END = 7, PLAYER_ANIM_RUN_L_LOOP = 8, PLAYER_ANIM_RUN_L_END = 9,
//    PLAYER_ANIM_RUN_R_LOOP = 10, PLAYER_ANIM_RUN_R_END = 11,
//
//    // ===== 걷기 애니메이션 (12-15) =====
//    PLAYER_ANIM_WALK_B_LOOP = 12, PLAYER_ANIM_WALK_F_LOOP = 13, PLAYER_ANIM_WALK_L_LOOP = 14,
//    PLAYER_ANIM_WALK_R_LOOP = 15,
//
//    // ===== 대기 애니메이션 (16-17) =====
//    PLAYER_ANIM_IDLE_LSWORD = 16, PLAYER_ANIM_IDLE_SPA = 17,
//
//    // ===== 스킬 애니메이션 (18-22) =====
//    PLAYER_ANIM_SKILL_BARRIER = 18, PLAYER_ANIM_SKILL_BUFF = 19, PLAYER_ANIM_SKILL_ENCHANT = 20,
//    PLAYER_ANIM_SKILL_GROUND = 21, PLAYER_ANIM_SKILL_SEARCH = 22,
//
//    // ===== 대검(TLSword) 회피 공격 (23-25) =====
//    PLAYER_ANIM_LS_ATK_DODGE_B = 23, PLAYER_ANIM_LS_ATK_DODGE_F = 24, PLAYER_ANIM_LS_ATK_DODGE_R = 25,
//
//    // ===== 대검 낙하 공격 (26-27) =====
//    PLAYER_ANIM_LS_ATK_FALL_END = 26, PLAYER_ANIM_LS_ATK_FALL_START = 27,
//
//    // ===== 대검 일반 공격 (28-36) =====
//    PLAYER_ANIM_LS_ATK_NORMAL1 = 28, PLAYER_ANIM_LS_ATK_NORMAL2 = 29, PLAYER_ANIM_LS_ATK_NORMAL3 = 30,
//    PLAYER_ANIM_LS_ATK_NORMAL4 = 31, PLAYER_ANIM_LS_ATK_NORMAL5 = 32, PLAYER_ANIM_LS_ATK_NORMAL6 = 33,
//    PLAYER_ANIM_LS_ATK_NORMAL7 = 34, PLAYER_ANIM_LS_ATK_NORMAL8 = 35, PLAYER_ANIM_LS_ATK_NORMAL9 = 36,
//
//    // ===== 대검 특수 공격 (37-40) =====
//    PLAYER_ANIM_LS_ATK_SP_DOWN2 = 37, PLAYER_ANIM_LS_ATK_SP_DOWN3 = 38, PLAYER_ANIM_LS_ATK_SP_DOWN = 39,
//    PLAYER_ANIM_LS_ATK_SP_LAUNCH = 40,
//
//    // ===== 대검 강공격 A타입 (41-56) =====
//    PLAYER_ANIM_LS_ATK_STRONG1A = 41, PLAYER_ANIM_LS_ATK_STRONG1B = 42, PLAYER_ANIM_LS_ATK_STRONG3A = 43,
//    PLAYER_ANIM_LS_ATK_STRONG4B = 44, PLAYER_ANIM_LS_ATK_STRONG5A = 45, PLAYER_ANIM_LS_ATK_STRONG6B = 46,
//    PLAYER_ANIM_LS_ATK_STRONG7A = 47, PLAYER_ANIM_LS_ATK_STRONG8B = 48, PLAYER_ANIM_LS_ATK_STRONG9A = 49,
//    PLAYER_ANIM_LS_ATK_STRONG10B = 50, PLAYER_ANIM_LS_ATK_STRONG11A = 51, PLAYER_ANIM_LS_ATK_STRONG12B = 52,
//    PLAYER_ANIM_LS_ATK_STRONG13A = 53, PLAYER_ANIM_LS_ATK_STRONG14B = 54, PLAYER_ANIM_LS_ATK_STRONG16B = 55,
//    PLAYER_ANIM_LS_ATK_STRONG18B = 56,
//
//    // ===== 대검 회피 (57-80) =====
//    PLAYER_ANIM_LS_DODGE_300_B = 57, PLAYER_ANIM_LS_DODGE_300_BL = 58, PLAYER_ANIM_LS_DODGE_300_BR = 59,
//    PLAYER_ANIM_LS_DODGE_300_F = 60, PLAYER_ANIM_LS_DODGE_300_FL = 61, PLAYER_ANIM_LS_DODGE_300_FR = 62,
//    PLAYER_ANIM_LS_DODGE_300_L = 63, PLAYER_ANIM_LS_DODGE_300_R = 64,
//
//    PLAYER_ANIM_LS_DODGE_PLUS_B = 65, PLAYER_ANIM_LS_DODGE_PLUS_BL = 66, PLAYER_ANIM_LS_DODGE_PLUS_BR = 67,
//    PLAYER_ANIM_LS_DODGE_PLUS_F = 68, PLAYER_ANIM_LS_DODGE_PLUS_FL = 69, PLAYER_ANIM_LS_DODGE_PLUS_FR = 70,
//    PLAYER_ANIM_LS_DODGE_PLUS_L = 71, PLAYER_ANIM_LS_DODGE_PLUS_R = 72,
//
//    PLAYER_ANIM_LS_DODGE_ROLL_B = 73, PLAYER_ANIM_LS_DODGE_ROLL_BL = 74, PLAYER_ANIM_LS_DODGE_ROLL_BR = 75,
//    PLAYER_ANIM_LS_DODGE_ROLL_F = 76, PLAYER_ANIM_LS_DODGE_ROLL_FL = 77, PLAYER_ANIM_LS_DODGE_ROLL_FR = 78,
//    PLAYER_ANIM_LS_DODGE_ROLL_L = 79, PLAYER_ANIM_LS_DODGE_ROLL_R = 80,
//
//    // ===== 대검 특수 회피 (81-88) =====
//    PLAYER_ANIM_LS_DODGE_SP_B = 81, PLAYER_ANIM_LS_DODGE_SP_BL = 82, PLAYER_ANIM_LS_DODGE_SP_BR = 83,
//    PLAYER_ANIM_LS_DODGE_SP_F = 84, PLAYER_ANIM_LS_DODGE_SP_FL = 85, PLAYER_ANIM_LS_DODGE_SP_FR = 86,
//    PLAYER_ANIM_LS_DODGE_SP_L = 87, PLAYER_ANIM_LS_DODGE_SP_R = 88,
//
//    // ===== 대검 가드 (89-93) =====
//    PLAYER_ANIM_LS_GUARD_END = 89, PLAYER_ANIM_LS_GUARD_LOOP = 90, PLAYER_ANIM_LS_GUARD_START = 91,
//    PLAYER_ANIM_LS_GUARD_BREAK = 92, PLAYER_ANIM_LS_GUARD_HIT = 93,
//
//    // ===== 검(TSword) 회피 공격 (94-96) =====
//    PLAYER_ANIM_S_ATK_DODGE_B = 94, PLAYER_ANIM_S_ATK_DODGE_F = 95, PLAYER_ANIM_S_ATK_DODGE_R = 96,
//
//    // ===== 검 낙하 공격 (97-98) =====
//    PLAYER_ANIM_S_ATK_FALL_END = 97, PLAYER_ANIM_S_ATK_FALL_START = 98,
//
//    // ===== 검 일반 공격 (99-114) =====
//    PLAYER_ANIM_S_ATK_NORMAL1 = 99, PLAYER_ANIM_S_ATK_NORMAL2 = 100, PLAYER_ANIM_S_ATK_NORMAL3 = 101,
//    PLAYER_ANIM_S_ATK_NORMAL4 = 102, PLAYER_ANIM_S_ATK_NORMAL5 = 103, PLAYER_ANIM_S_ATK_NORMAL6 = 104,
//    PLAYER_ANIM_S_ATK_NORMAL7 = 105, PLAYER_ANIM_S_ATK_NORMAL8 = 106, PLAYER_ANIM_S_ATK_NORMAL9 = 107,
//    PLAYER_ANIM_S_ATK_NORMAL10 = 108, PLAYER_ANIM_S_ATK_NORMAL11 = 109, PLAYER_ANIM_S_ATK_NORMAL12 = 110,
//    PLAYER_ANIM_S_ATK_NORMAL13 = 111, PLAYER_ANIM_S_ATK_NORMAL14 = 112, PLAYER_ANIM_S_ATK_NORMAL15 = 113,
//    PLAYER_ANIM_S_ATK_NORMAL16 = 114,
//
//    // ===== 검 기타 공격 (115-120) =====
//    PLAYER_ANIM_S_ATK_REPEL = 115, PLAYER_ANIM_S_ATK_SP_DOWN2 = 116, PLAYER_ANIM_S_ATK_SP_DOWN3 = 117,
//    PLAYER_ANIM_S_ATK_SP_DOWN4 = 118, PLAYER_ANIM_S_ATK_SP_DOWN = 119, PLAYER_ANIM_S_ATK_SP_LAUNCH = 120,
//
//    // ===== 검 강공격 (121-135) =====
//    PLAYER_ANIM_S_ATK_STRONG1A = 121, PLAYER_ANIM_S_ATK_STRONG1B = 122, PLAYER_ANIM_S_ATK_STRONG3A = 123,
//    PLAYER_ANIM_S_ATK_STRONG4B = 124, PLAYER_ANIM_S_ATK_STRONG6A = 125, PLAYER_ANIM_S_ATK_STRONG6B = 126,
//    PLAYER_ANIM_S_ATK_STRONG7A = 127, PLAYER_ANIM_S_ATK_STRONG7B = 128, PLAYER_ANIM_S_ATK_STRONG8B = 129,
//    PLAYER_ANIM_S_ATK_STRONG9A = 130, PLAYER_ANIM_S_ATK_STRONG10B = 131, PLAYER_ANIM_S_ATK_STRONG12B = 132,
//    PLAYER_ANIM_S_ATK_STRONG14A = 133, PLAYER_ANIM_S_ATK_STRONG14B = 134, PLAYER_ANIM_S_ATK_STRONG16A = 135,
//
//    // ===== 검 가드 (136-140) =====
//    PLAYER_ANIM_S_GUARD_END = 136, PLAYER_ANIM_S_GUARD_LOOP = 137, PLAYER_ANIM_S_GUARD_START = 138,
//    PLAYER_ANIM_S_GUARD_BREAK = 139, PLAYER_ANIM_S_GUARD_HIT = 140,
//
//    PLAYER_ANIM_END
//};
//NS_END

NS_BEGIN(Client)

// 코드베인 스타일 플레이어 애니메이션 키 정의 (간소화 버전)
enum PLAYER_ANIMATION_KEY
{
    // ===== 피해 애니메이션 (0-3) =====
    PLAYER_ANIM_DAMAGE_B = 0, PLAYER_ANIM_DAMAGE_F = 1, PLAYER_ANIM_DAMAGE_L = 2,
    PLAYER_ANIM_DAMAGE_R = 3,

    // ===== 달리기 애니메이션 (4-11) =====
    PLAYER_ANIM_RUN_B_LOOP = 4, PLAYER_ANIM_RUN_B_END = 5, PLAYER_ANIM_RUN_F_LOOP = 6,
    PLAYER_ANIM_RUN_F_END = 7, PLAYER_ANIM_RUN_L_LOOP = 8, PLAYER_ANIM_RUN_L_END = 9,
    PLAYER_ANIM_RUN_R_LOOP = 10, PLAYER_ANIM_RUN_R_END = 11,

    // ===== 대기 애니메이션 (12-13) =====
    PLAYER_ANIM_IDLE_LSWORD = 12, PLAYER_ANIM_IDLE_SPA = 13,

    // ===== 강화 공격 스킬 (14-24) =====
    PLAYER_ANIM_SKILL_STRONG1 = 14, PLAYER_ANIM_SKILL_STRONG2 = 15, PLAYER_ANIM_SKILL_STRONG3 = 16,
    PLAYER_ANIM_SKILL_STRONG4 = 17, PLAYER_ANIM_SKILL_STRONG5 = 18, PLAYER_ANIM_SKILL_STRONG6 = 19,
    PLAYER_ANIM_SKILL_STRONG7 = 20, PLAYER_ANIM_SKILL_STRONG9 = 21, PLAYER_ANIM_SKILL_STRONG10 = 22,
    PLAYER_ANIM_SKILL_STRONG11 = 23, PLAYER_ANIM_SKILL_STRONG12 = 24,

    // ===== 기본 스킬 애니메이션 (25-29) =====
    PLAYER_ANIM_SKILL_BARRIER = 25, PLAYER_ANIM_SKILL_BUFF = 26, PLAYER_ANIM_SKILL_ENCHANT = 27,
    PLAYER_ANIM_SKILL_GROUND = 28, PLAYER_ANIM_SKILL_SEARCH = 29,

    // ===== 대검(TLSword) 일반 공격 (30-38) =====
    PLAYER_ANIM_LS_ATK_NORMAL1 = 30, PLAYER_ANIM_LS_ATK_NORMAL2 = 31, PLAYER_ANIM_LS_ATK_NORMAL3 = 32,
    PLAYER_ANIM_LS_ATK_NORMAL4 = 33, PLAYER_ANIM_LS_ATK_NORMAL5 = 34, PLAYER_ANIM_LS_ATK_NORMAL6 = 35,
    PLAYER_ANIM_LS_ATK_NORMAL7 = 36, PLAYER_ANIM_LS_ATK_NORMAL8 = 37, PLAYER_ANIM_LS_ATK_NORMAL9 = 38,

    // ===== 대검 특수 공격 (39-42) =====
    PLAYER_ANIM_LS_ATK_SP_DOWN2 = 39, PLAYER_ANIM_LS_ATK_SP_DOWN3 = 40, PLAYER_ANIM_LS_ATK_SP_DOWN = 41,
    PLAYER_ANIM_LS_ATK_SP_LAUNCH = 42,

    // ===== 대검 강공격 (43-51) =====
    PLAYER_ANIM_LS_ATK_STRONG1A = 43, PLAYER_ANIM_LS_ATK_STRONG1B = 44, PLAYER_ANIM_LS_ATK_STRONG3A = 45,
    PLAYER_ANIM_LS_ATK_STRONG4B = 46, PLAYER_ANIM_LS_ATK_STRONG5A = 47, PLAYER_ANIM_LS_ATK_STRONG6B = 48,
    PLAYER_ANIM_LS_ATK_STRONG7A = 49, PLAYER_ANIM_LS_ATK_STRONG8B = 50, PLAYER_ANIM_LS_ATK_STRONG9A = 51,

    // ===== 대검 롤 회피 (52-59) =====
    PLAYER_ANIM_LS_DODGE_ROLL_B = 52, PLAYER_ANIM_LS_DODGE_ROLL_BL = 53, PLAYER_ANIM_LS_DODGE_ROLL_BR = 54,
    PLAYER_ANIM_LS_DODGE_ROLL_F = 55, PLAYER_ANIM_LS_DODGE_ROLL_FL = 56, PLAYER_ANIM_LS_DODGE_ROLL_FR = 57,
    PLAYER_ANIM_LS_DODGE_ROLL_L = 58, PLAYER_ANIM_LS_DODGE_ROLL_R = 59,

    // ===== 대검 특수 회피 (60-67) =====
    PLAYER_ANIM_LS_DODGE_SP_B = 60, PLAYER_ANIM_LS_DODGE_SP_BL = 61, PLAYER_ANIM_LS_DODGE_SP_BR = 62,
    PLAYER_ANIM_LS_DODGE_SP_F = 63, PLAYER_ANIM_LS_DODGE_SP_FL = 64, PLAYER_ANIM_LS_DODGE_SP_FR = 65,
    PLAYER_ANIM_LS_DODGE_SP_L = 66, PLAYER_ANIM_LS_DODGE_SP_R = 67,

    // ===== 대검 가드 (68-72) =====
    PLAYER_ANIM_LS_GUARD_END = 68, PLAYER_ANIM_LS_GUARD_LOOP = 69, PLAYER_ANIM_LS_GUARD_START = 70,
    PLAYER_ANIM_LS_GUARD_BREAK = 71, PLAYER_ANIM_LS_GUARD_HIT = 72,

    // ===== 검(TSword) 회피 공격 (73-75) =====
    PLAYER_ANIM_S_ATK_DODGE_B = 73, PLAYER_ANIM_S_ATK_DODGE_F = 74, PLAYER_ANIM_S_ATK_DODGE_R = 75,

    // ===== 검 낙하 공격 (76-77) =====
    PLAYER_ANIM_S_ATK_FALL_END = 76, PLAYER_ANIM_S_ATK_FALL_START = 77,

    // ===== 검 일반 공격 (78-93) =====
    PLAYER_ANIM_S_ATK_NORMAL1 = 78, PLAYER_ANIM_S_ATK_NORMAL2 = 79, PLAYER_ANIM_S_ATK_NORMAL3 = 80,
    PLAYER_ANIM_S_ATK_NORMAL4 = 81, PLAYER_ANIM_S_ATK_NORMAL5 = 82, PLAYER_ANIM_S_ATK_NORMAL6 = 83,
    PLAYER_ANIM_S_ATK_NORMAL7 = 84, PLAYER_ANIM_S_ATK_NORMAL8 = 85, PLAYER_ANIM_S_ATK_NORMAL9 = 86,
    PLAYER_ANIM_S_ATK_NORMAL10 = 87, PLAYER_ANIM_S_ATK_NORMAL11 = 88, PLAYER_ANIM_S_ATK_NORMAL12 = 89,
    PLAYER_ANIM_S_ATK_NORMAL13 = 90, PLAYER_ANIM_S_ATK_NORMAL14 = 91, PLAYER_ANIM_S_ATK_NORMAL15 = 92,
    PLAYER_ANIM_S_ATK_NORMAL16 = 93,

    // ===== 검 기타 공격 (94-99) =====
    PLAYER_ANIM_S_ATK_REPEL = 94, PLAYER_ANIM_S_ATK_SP_DOWN2 = 95, PLAYER_ANIM_S_ATK_SP_DOWN3 = 96,
    PLAYER_ANIM_S_ATK_SP_DOWN4 = 97, PLAYER_ANIM_S_ATK_SP_DOWN = 98, PLAYER_ANIM_S_ATK_SP_LAUNCH = 99,

    // ===== 검 가드 (100-104) =====
    PLAYER_ANIM_S_GUARD_END = 100, PLAYER_ANIM_S_GUARD_LOOP = 101, PLAYER_ANIM_S_GUARD_START = 102,
    PLAYER_ANIM_S_GUARD_BREAK = 103, PLAYER_ANIM_S_GUARD_HIT = 104,

    PLAYER_ANIM_END
};

NS_END