#pragma once


#pragma once

NS_BEGIN(Client)

// TStdKnight 애니메이션 키 정의
enum TSTDKNIGHT_ANIMATION_KEY : _uint
{
    // ===== 데미지 애니메이션 (0-18) =====
    KNIGHT_DAMAGE_BL_01 = 0, KNIGHT_DAMAGE_BR_01 = 1, KNIGHT_DAMAGE_FL_01 = 2,
    KNIGHT_DAMAGE_BL_02 = 3, KNIGHT_DAMAGE_BR_02 = 4, KNIGHT_DAMAGE_FL_02 = 5,
    KNIGHT_DAMAGE_FR_02 = 6, KNIGHT_DAMAGE_BL_03 = 7, KNIGHT_DAMAGE_BR_03 = 8,

    KNIGHT_DAMAGE_FL_03 = 9, KNIGHT_DAMAGE_FR_03 = 10, KNIGHT_DAMAGE_BACKSTAB = 11,
    KNIGHT_DAMAGE_BLOW_B = 12, KNIGHT_DAMAGE_BLOW_F = 13, KNIGHT_DAMAGE_STRIKE_P = 14,

    // ===== 죽음 애니메이션 (15-16) =====
    KNIGHT_DEATH_F = 15, KNIGHT_DEATH_N = 16,

    // ===== 다운 상태 애니메이션 (17-18) =====
    KNIGHT_DOWN_P_END = 17, KNIGHT_DOWN_P_LOOP = 18,

    // ===== 라이트 소드 공격 애니메이션 (19-27)sawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww =====
    KNIGHT_LSWORD_KICK = 19, KNIGHT_LSWORD_NORMAL_01 = 20, KNIGHT_LSWORD_NORMAL_02 = 21,
    KNIGHT_LSWORD_NORMAL_03 = 22, KNIGHT_LSWORD_SMASH = 23, KNIGHT_LSWORD_STRONG_01 = 24,
    KNIGHT_LSWORD_STRONG_02 = 25, KNIGHT_LSWORD_STRONG_03 = 26, KNIGHT_LSWORD_SWING = 27,

    // ===== 라이트 소드 대기 애니메이션 (28) =====
    KNIGHT_LSWORD_IDLE = 28,

    // ===== 쉴드+라이트소드 가드 애니메이션 (29-30) =====
    KNIGHT_SHIELD_LSWORD_GUARD_END = 29, KNIGHT_SHIELD_LSWORD_GUARD_START = 30,

    // ===== 쉴드+소드 공격 애니메이션 (31-36) =====
    KNIGHT_SHIELD_SWORD_BEHIND_BASH = 31, KNIGHT_SHIELD_SWORD_ATTACK_01 = 32, KNIGHT_SHIELD_SWORD_ATTACK_02A = 33,
    KNIGHT_SHIELD_SWORD_ATTACK_02B = 34, KNIGHT_SHIELD_SWORD_ATTACK_02C = 35, KNIGHT_SHIELD_SWORD_ATTACK_02D = 36,

    // ===== 쉴드+소드 방어 애니메이션 (37-44) =====
    KNIGHT_SHIELD_SWORD_BASH = 37, KNIGHT_SHIELD_SWORD_GUARD_TURN_L180 = 38, KNIGHT_SHIELD_SWORD_GUARD_TURN_L90 = 39,
    KNIGHT_SHIELD_SWORD_GUARD_TURN_R180 = 40, KNIGHT_SHIELD_SWORD_GUARD_TURN_R90 = 41, KNIGHT_SHIELD_SWORD_GUARD_END = 42,

    KNIGHT_SHIELD_SWORD_GUARD_LOOP = 43, KNIGHT_SHIELD_SWORD_GUARD_START = 44,

    // ===== 쉴드+소드 이동 애니메이션 (45-55) =====
    KNIGHT_SHIELD_SWORD_GUARD_RUN_F = 45, KNIGHT_SHIELD_SWORD_GUARD_WALK_B = 46, KNIGHT_SHIELD_SWORD_GUARD_WALK_BL = 47,
    KNIGHT_SHIELD_SWORD_GUARD_WALK_BR_L = 48, KNIGHT_SHIELD_SWORD_GUARD_WALK_BR_R = 49, KNIGHT_SHIELD_SWORD_GUARD_WALK_F = 50,
    KNIGHT_SHIELD_SWORD_GUARD_WALK_FL_L = 51, KNIGHT_SHIELD_SWORD_GUARD_WALK_FL_R = 52, KNIGHT_SHIELD_SWORD_GUARD_WALK_FR = 53,

    KNIGHT_SHIELD_SWORD_GUARD_WALK_L = 54, KNIGHT_SHIELD_SWORD_GUARD_WALK_R = 55,

    // ===== 쉴드+소드 방어 관련 애니메이션 (56-59) =====
    KNIGHT_SHIELD_SWORD_GUARD_BREAK = 56, KNIGHT_SHIELD_SWORD_GUARD_HIT_01 = 57, KNIGHT_SHIELD_SWORD_GUARD_HIT_02 = 58,
    KNIGHT_SHIELD_SWORD_SHIELD_BLOW = 59,

    // ===== 소드 공격 애니메이션 (60-75) =====
    KNIGHT_SWORD_ATTACK_JUMP = 60, KNIGHT_SWORD_ATTACK_NORMAL_00 = 61, KNIGHT_SWORD_ATTACK_NORMAL_01 = 62,
    KNIGHT_SWORD_ATTACK_NORMAL_02 = 63, KNIGHT_SWORD_ATTACK_NORMAL_03 = 64, KNIGHT_SWORD_ATTACK_NORMAL_03B = 65,
    KNIGHT_SWORD_ATTACK_RAISEUP = 66, KNIGHT_SWORD_ATTACK_RANGE = 67, KNIGHT_SWORD_ATTACK_SPECIAL_01 = 68,

    KNIGHT_SWORD_ATTACK_SPECIAL_02 = 69, KNIGHT_SWORD_ATTACK_SPECIAL_03_END = 70, KNIGHT_SWORD_ATTACK_SPECIAL_03_LOOP = 71,
    KNIGHT_SWORD_ATTACK_SPECIAL_03_START = 72, KNIGHT_SWORD_ATTACK_STRONG_01 = 73, KNIGHT_SWORD_ATTACK_STRONG_02 = 74,
    KNIGHT_SWORD_ATTACK_STRONG_03 = 75,

    // ===== 소드 대기 애니메이션 (76) =====
    KNIGHT_SWORD_IDLE = 76,

    KNIGHT_ANIMATION_END
};

NS_END