#pragma once

NS_BEGIN(Client)

// ========== SlaveVampire 애니메이션 Enum 분류 ==========
enum SLAVEVAMPIRE_ANIMATION_KEY : _uint
{
    // ===== 피해 애니메이션 (Damage) =====
    SLAVEVAMPIRE_DAMAGE01_BL = 0, SLAVEVAMPIRE_DAMAGE01_BR = 1, SLAVEVAMPIRE_DAMAGE01_FL = 2,
    SLAVEVAMPIRE_DAMAGE01_FR = 3, SLAVEVAMPIRE_DAMAGE02_BL_02 = 4, SLAVEVAMPIRE_DAMAGE02_BR_02 = 5,
    SLAVEVAMPIRE_DAMAGE02_FL_02 = 6, SLAVEVAMPIRE_DAMAGE02_FR_02 = 7, SLAVEVAMPIRE_DAMAGE03_BL = 8,
    SLAVEVAMPIRE_DAMAGE03_BL_02 = 9, SLAVEVAMPIRE_DAMAGE03_BR = 10, SLAVEVAMPIRE_DAMAGE03_BR_02 = 11,
    SLAVEVAMPIRE_DAMAGE03_FL = 12, SLAVEVAMPIRE_DAMAGE03_FL_02 = 13, SLAVEVAMPIRE_DAMAGE03_FR = 14,
    SLAVEVAMPIRE_DAMAGE03_FR_02 = 15,

    // ===== 죽음 애니메이션 (Death) =====
    SLAVEVAMPIRE_DEATH_B = 16, SLAVEVAMPIRE_DEATH_F = 17, SLAVEVAMPIRE_DEATH_N = 18,

    // ===== 이동 애니메이션 (Movement) =====
    SLAVEVAMPIRE_RUN_F_LOOP = 19, SLAVEVAMPIRE_WALK_B_LOOP = 20, SLAVEVAMPIRE_WALK_BL_LOOP = 21,
    SLAVEVAMPIRE_WALK_BR_LEFT_LOOP = 22, SLAVEVAMPIRE_WALK_BR_RIGHT_LOOP = 23, SLAVEVAMPIRE_WALK_F_LOOP = 24,
    SLAVEVAMPIRE_WALK_FL_LEFT_LOOP = 25, SLAVEVAMPIRE_WALK_FL_RIGHT_LOOP = 26, SLAVEVAMPIRE_WALK_FR_LOOP = 27,
    SLAVEVAMPIRE_WALK_L_LOOP = 28, SLAVEVAMPIRE_WALK_R_LOOP = 29,

    // ===== 벽 관련 애니메이션 (Wall Actions) =====
    SLAVEVAMPIRE_WALLCLIMB_FIST = 30, SLAVEVAMPIRE_WALLCLIMB_HALBERD = 31, SLAVEVAMPIRE_WALLCLIMB_HAMMER = 32,
    SLAVEVAMPIRE_WALLCLIMB_SWORD = 33, SLAVEVAMPIRE_WALLFALL_LANDING_LOOP = 34, SLAVEVAMPIRE_WALLFALL_LANDING_START = 35,
    SLAVEVAMPIRE_WALLFALL_LANDING_FIST_END = 36, SLAVEVAMPIRE_WALLFALL_LANDING_HALBERD_END = 37, SLAVEVAMPIRE_WALLFALL_LANDING_SWORD_END = 38,
    SLAVEVAMPIRE_WALL_IDLE_LOOP = 39,

    // ===== 대검 공격 애니메이션 (Large Sword Attacks) =====
    SLAVEVAMPIRE_LSWORD_NORMAL01 = 40, SLAVEVAMPIRE_LSWORD_NORMAL02 = 41, SLAVEVAMPIRE_LSWORD_POWERFUL01 = 42,
    SLAVEVAMPIRE_LSWORD_POWERFUL01B = 43, SLAVEVAMPIRE_LSWORD_SPECIAL01 = 44, SLAVEVAMPIRE_LSWORD_SPECIAL02 = 45,
    SLAVEVAMPIRE_LSWORD_SPECIAL03 = 46, SLAVEVAMPIRE_LSWORD_SPECIAL04 = 47, SLAVEVAMPIRE_LSWORD_SPECIAL05 = 48,
    SLAVEVAMPIRE_LSWORD_STRONG01 = 49, SLAVEVAMPIRE_LSWORD_STRONG02 = 50, SLAVEVAMPIRE_LSWORD_STRONG03 = 51,
    SLAVEVAMPIRE_LSWORD_IDLE_LOOP = 52,

    // ===== 검 공격 애니메이션 (Sword Attacks) =====
    SLAVEVAMPIRE_SWORD_NORMAL00 = 53, SLAVEVAMPIRE_SWORD_NORMAL01 = 54, SLAVEVAMPIRE_SWORD_NORMAL02 = 55,
    SLAVEVAMPIRE_SWORD_SPECIAL01 = 56, SLAVEVAMPIRE_SWORD_SPECIAL02 = 57, SLAVEVAMPIRE_SWORD_SPECIAL03_END = 58,
    SLAVEVAMPIRE_SWORD_SPECIAL03_LOOP = 59, SLAVEVAMPIRE_SWORD_SPECIAL03_START = 60, SLAVEVAMPIRE_SWORD_SPECIAL04 = 61,
    SLAVEVAMPIRE_SWORD_SPECIAL05 = 62, SLAVEVAMPIRE_SWORD_SPECIAL06 = 63, SLAVEVAMPIRE_SWORD_SPECIAL07 = 64,
    SLAVEVAMPIRE_SWORD_STRONG01 = 65, SLAVEVAMPIRE_SWORD_STRONG02 = 66, SLAVEVAMPIRE_SWORD_THROWING01 = 67,
    SLAVEVAMPIRE_SWORD_THROWING02 = 68, SLAVEVAMPIRE_SWORD_IDLE_LOOP = 69,

    // ===== 비전투 기본 상태 (Non-Fight Idle States) =====
    SLAVEVAMPIRE_NONFIGHT_IDLE_LOOP = 70, SLAVEVAMPIRE_NONFIGHT_IDLE_EAT_LOOP = 71, SLAVEVAMPIRE_NONFIGHT_IDLE_SIT_LOOP = 72,
    SLAVEVAMPIRE_NONFIGHT_IDLE_SIT_TEST = 73, SLAVEVAMPIRE_NONFIGHT_IDLE_SLEEP_LOOP = 74,

    // ===== 비전투 회전 (Non-Fight Turns) =====
    SLAVEVAMPIRE_NONFIGHT_TURN_L180 = 75, SLAVEVAMPIRE_NONFIGHT_TURN_L90 = 76, SLAVEVAMPIRE_NONFIGHT_TURN_R180 = 77,
    SLAVEVAMPIRE_NONFIGHT_TURN_R90 = 78,

    // ===== 비전투 위협 행동 (Non-Fight Threats) =====
    SLAVEVAMPIRE_NONFIGHT_THREAT01 = 79, SLAVEVAMPIRE_NONFIGHT_THREAT02 = 80, SLAVEVAMPIRE_NONFIGHT_THREAT03 = 81,
    SLAVEVAMPIRE_NONFIGHT_THREAT04 = 82, SLAVEVAMPIRE_NONFIGHT_THREAT_EAT_F = 83, SLAVEVAMPIRE_NONFIGHT_THREAT_SIT_F = 84,
    SLAVEVAMPIRE_NONFIGHT_THREAT_SLEEP_F = 85, SLAVEVAMPIRE_NONFIGHT_WALK_LOOP = 86,

    SLAVEVAMPIRE_ANIMATION_END
};
NS_END